### ISSUE TITLE
How to calculate D-ECE

### ISSUE THREAD

**Issue by nisargshah1999** [akhtarvision/bpc_calibration#1]
Hi: Thanks for sharing code and interesting contribution
How can I evaluate D-ECE in your predictions,  it would be good if you could share the code or suggest a way to evaluate it; some ideas to move forward should be useful
Thanks

**Comment by akhtarvision** [comment]
> 

Thank you for your interest. Please follow guidelines [here](https://github.com/akhtarvision/bpc_calibration#d-ece-evaluation)
You need to input det files along with imageids.

**Comment by akhilpm** [comment]
Thanks, Akhtar for sharing the code. Is it possible for you to share the code snippet you used for the D-ECE computation?

**Comment by akhtarvision** [comment]
Duplicate. Follow the [link](https://github.com/akhtarvision/cal-detr/issues/2)
